"""empty message

Revision ID: 92d407c5a902
Revises: beacd0de013f
Create Date: 2024-01-04 16:10:58.181791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92d407c5a902'
down_revision: Union[str, None] = 'beacd0de013f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thread', sa.Column('view', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thread', 'view')
    # ### end Alembic commands ###
